target-version = "py314"

[lint]
ignore = [
"BLE001",
"COM812",
"D",
"E731",
"EM102",
"ERA001",
"F811",
"INP001",
"PLC0415",
"PLR2004",
"RUF",
"S105",
"S311",
"TRY003",
]
select = ["ALL"]
fixable = ["ALL"]
